CREATE TABLE mytable(
   Nom               VARCHAR(25) NOT NULL PRIMARY KEY
  ,Fondateur         VARCHAR(76)
  ,Annee_de_creation INTEGER 
  ,Siege             VARCHAR(37)
);
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Gigamic','Stéphane, Ludovic, et Jean-Christophe Gires',1991,'Wimereux (Boulogne-sur-mer)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Sorry we are French','Emmanuel Beltrando',2017,NULL);
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Studio H','Hicham Ayoub Bedran',2019,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Abysse Corp','Xavier Sartoris, René Gréville',1999,'Grand-Couronne (Rouen)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Bioviva éditions','Jean-Thierry Winstel',1996,'Montpellier');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Djeco','Véronique Ceillier',1954,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Dujardin','Edmond Dujardin',1951,'Cestas (Bordeaux)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Ferriot Cric','Famille Ferriot',1928,'Mussy-sur-Seine');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Lansay','Elie Azoulai',1972,'Argenteuil (Val-d''Oise)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Mégableu','Pascal Esnol',1994,'Randonnai (Orne)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('TF1 Games','TF1',2001,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Ankama','Ankama',2006,'Roubaix (Nord)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Asyncron','Olivier Chanry, Thierry Mattray, Franck Saverys',2008,'Tourcoing (Nord)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('ATM Gaming','Benjamin Brissy, 
Jean-Baptiste Campion',2018,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Bankiiiz Editions','Bertrand Arpino, Stéphane Escapa',2015,'Lyon');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Blamé!','Sébastien Gaspard, Christophe Mercier',2015,'Sillingy (Haute-Savoie)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Blue Cocker','Alain Balay',2013,'Toulouse');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Blue Orange (Europe)','Timothée Leroy',2005,'Pont-é-Mousson (Meurthe-et-Mos.)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Bombyx','Erwan Hascéet, Loég Hascéet',2011,'Quimper');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Capsicum Games','Didier Dincher',2013,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Catch Up Games','Sébastien Kihm, Clément Milker',2014,'Lyon');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Chouic','Antoine Habert, Romuald Percereau',2015,'Nantes');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Cocktail Games','Matthieu d''Epenoux',2001,'Versailles');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Cosmoludo Games','Tom & Pierre Delahaye',2019,'Soudorgues - Cévennes');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Débécle Jeux','Emmanuel Soulié et Julien Teilhet',2018,'Saint-Thibéry');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Devil Pig',NULL,2013,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Disto Studio','Maria Paloma Sanchez et Luc Anuszewski',2019,'Strasbourg');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Elements Editions','Cédric Duwelz',2013,'Monaco');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Elemon Games','Joannes Roussel',2013,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Euphoria Games',NULL,NULL,'Lille');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Ferti','Cédric Huet',2001,'Mérignac (Bordeaux)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Flip Flap','Cyril Blondel',2013,NULL);
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Funforge','Philippe Nouhra',2008,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Grosso Modo','Guillaume Goujon, Arnaud Pierru',2011,'Brunoy (Essonne)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Grrre Games','Céline et Florian Grenier',2018,'Grenoble (Isére)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Hexasim','Christophe Gentil-Perret',2008,'Annecy');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Hiboutatillus','Louis Roudaut, Thibault Lorcy',2014,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Holy Grail Games','Jamie Johnson, Olivier Melison, Vincent Dutrait',2016,'Nancy');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Hubvious Games','Matthieu Perreard, Cédric Sanchez',2017,'Lyon');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Id&aL','Igor Davin, Antoine Laboureur',2008,'Montpellier (Hérault)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Iello','Cédric Barbé, Patrice Boulet',2004,'Heillecourt (Nancy)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Ilopeli','Arnaud Urbon',2011,'Voisins-le-Bretonneux (Yvelines)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('In Ludo Veritas','Christophe Hermier',2007,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Jeux Opla','Florent Toscano',2010,'Lyon');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Jocus','Jean-Pierre Nicolas',2015,'Bordeaux');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('La Boite de Jeu','Benoit Bannier, Benjamin Carayon, Timothée Gibelin',2013,'Lyon');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('La Haute Roche','Sylvie Barc, Dominique Granger',2002,'Ladignac-le-Long
(Haute-Vienne)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Le Droit de perdre','Franéois Lang, Fabien Bleuze, Yves Hirschfeld',2007,'Antony (Hauts-de-Seine)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Les Jeux du Lacé[archive]','Franck Régnier',2015,'Annecy (Haute Savoie)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Libellud','Régis Bonnessée',2008,'Poitiers');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Ludically','Christophe Boelinger, Jean-Charles Mourey',2009,'Valbonne (Nice)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Ludonaute','Cédric et Anne-Cécile Lefebvre',2010,'Istres (Bouches-du-Rhéne)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Lui-méme','Philippe des Palliéres',1999,'St-Pére-en-Retz (Loire-Atlantique)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Lumberjacks Studio','Antoine Roffe',2016,'Vendes');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Matagot','Hicham Ayoub-Bedran',2005,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Morning','Tim Dumain, Valentin Famose',2011,'Toulouse');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Nuts! Publishing','Florent Coupeau, Claude Le Roy, Arnaud Moyon, Thomas Pouchin, Nicolas Rident',2011,'Quimper (Finistére)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('OldChap Games','Paul-Adrien Tournier, Jean-Baptiste Fremaux, Thomas Luzurier',2011,'Toulouse');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Origames','Guillaume Gille-Naves, Igor Polouchine, Rodolphe Gilbart',2010,'Boulogne-Billancourt
(Hauts-de-Seine)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Oya','Patrick Ruttner',1995,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Paille éditions','Yves Renou',2000,'Le Vigen (Limoges)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('PARIA','David et Alexandre Rousseau',2019,'Chéteauroux');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Pink Monkey Games','Julien Percot',2016,'Vigneux-de-Bretagne');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Purple Brain Créations','Benoit Forget',2013,'Parthenay (Deux-Sévres)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Récréadim','Cécile Balaé',2009,'Viroflay (Yvelines)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Robin Red Gamesé[archive]','Pascal Boucher',2012,'Allassac (Corréze)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Runes Editions','Rémi Gruber',2014,'Solers (Seine-et-Marne)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Sentosphére','Véronique Debroise',1989,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Serious Poulp','Ludovic Roudy, Bruno Sautter',2010,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Subverti','Yoann Brogol',2018,'Toulouse');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Superlude','Antoine Davrou',2013,'Yerres (Essonne)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Super Meeple','Charles Perret, Alexandre Pierru, Arnaud Pierru',2015,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Sweet November','Didier Jacobée, Patrick Rieder',2010,'Chéteaudun (Eure-et-Loir)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Zoé Yatéka Créations','Jean-Luc et Andréa Renaud',2010,'Saint-Michel-sur-Orge (Essonne)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Asmodee','Marc Nunés, Philippe Mouret, Croc',1995,'Guyancourt (Versailles)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Days of Wonder','Eric Hautemont, Mark Kaufmann',2002,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Edge Entertainment','Gilles Garnier',2004,'St-Jean (Toulouse)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Space Cowboys','Asmodee',2013,'Buc (Yvelines)');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Ystari','Cyril Demaegd',2003,'Paris');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Fantasy Flight Games','Christian T. Petersen',NULL,'Roseville, Minnesota');
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Mayfair Games',NULL,1982,NULL);
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Plaid Hat Games',NULL,NULL,NULL);
INSERT INTO mytable(Nom,Fondateur,Annee_de_creation,Siege) VALUES ('Z-Man Games','Zev Schlasinger',1999,'Carmel, New York');
